# Generated by Django 3.2.22 on 2023-10-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthorisedQuoteRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_nameORcompany_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('support', 'Support'), ('hardware', 'Hardware'), ('Software', 'Software'), ('microsoft', 'Microsoft'), ('power_solutions', 'Power Solutions')], max_length=100)),
            ],
        ),
    ]
