# Generated by Django 3.2.22 on 2023-10-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_genepool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthorisedquoterequests',
            name='phone',
            field=models.CharField(blank=True, default='No phone provided', max_length=15),
        ),
        migrations.AlterField(
            model_name='unauthorisedquoterequests',
            name='service',
            field=models.CharField(blank=True, choices=[('support', 'Support'), ('hardware', 'Hardware'), ('software', 'Software'), ('microsoft', 'Microsoft'), ('power_solutions', 'Power Solutions')], max_length=20),
        ),
    ]
