# Generated by Django 3.2.22 on 2023-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_genepool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthorisedquoterequests',
            name='status',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Open'), ('Completed', 'Closed')], default='Ongoing', max_length=20),
        ),
    ]
