# Generated by Django 3.2.22 on 2023-10-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_genepool', '0002_auto_20231024_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='unauthorisedquoterequests',
            name='request_description',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
