# Generated by Django 3.2.3 on 2024-01-29 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_genepool', '0002_alter_unauthorisedquoterequests_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthorisedCallBackRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_nameORcompany_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='No phone provided', max_length=15)),
                ('request_description', models.CharField(blank=True, max_length=800)),
                ('service', models.CharField(blank=True, choices=[('support', 'Support'), ('hardware', 'Hardware'), ('software', 'Software'), ('microsoft', 'Microsoft'), ('power_solutions', 'Power Solutions')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Ongoing', 'Open'), ('Completed', 'Closed')], default='Ongoing', max_length=20)),
                ('time_requested', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
