# Generated by Django 3.2.3 on 2024-02-13 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_genepool', '0003_unauthorisedcallbackrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorisedQuoteRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_nameORcompany_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='No phone provided', max_length=15)),
                ('request_description', models.CharField(blank=True, max_length=800)),
                ('service', models.CharField(blank=True, choices=[('support', 'Support'), ('hardware', 'Hardware'), ('software', 'Software'), ('microsoft', 'Microsoft'), ('power_solutions', 'Power Solutions')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Ongoing', 'Open'), ('Completed', 'Closed')], default='Ongoing', max_length=20)),
                ('time_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
