# Generated by Django 3.2.3 on 2024-02-19 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_genepool', '0008_alter_authorisedquoterequests_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorisedTicketRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_nameORcompany_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('time_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_description', models.CharField(blank=True, max_length=800)),
                ('status', models.CharField(blank=True, choices=[('Unanswered', 'Unanswered'), ('Answered', 'Answered'), ('Closed', 'Closed')], default='Unanswered', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('staff_members_who_replied', models.ManyToManyField(blank=True, related_name='replied_staff_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Staff Members Who Replied')),
            ],
        ),
        migrations.AlterField(
            model_name='authorisedquoterequests',
            name='status',
            field=models.CharField(blank=True, choices=[('Unanswered', 'Unanswered'), ('Answered', 'Answered'), ('Closed', 'Closed')], default='Unanswered', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='../GENEPOOL/templates/ticket-files/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='app_genepool.authorisedticketrequests')),
            ],
        ),
    ]
