# Generated by Django 3.2.3 on 2024-03-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_genepool', '0010_auto_20240220_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorisedticketrequests',
            name='email',
        ),
        migrations.AlterField(
            model_name='chatdialogue',
            name='file',
            field=models.FileField(blank=True, upload_to='GENEPOOL/templates/ticket-files/'),
        ),
    ]
