# Generated by Django 3.2.3 on 2024-03-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_genepool', '0011_auto_20240314_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorisedQuoteRequests',
        ),
    ]
