# Generated by Django 3.2.3 on 2024-03-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_genepool', '0012_delete_authorisedquoterequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorisedticketrequests',
            name='request_description',
            field=models.CharField(max_length=800),
        ),
    ]
