# Generated by Django 3.2.3 on 2024-03-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_genepool', '0014_auto_20240328_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='unauthorisedcallbackrequests',
            name='closed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Closed_requests_Callback', to='auth.user', verbose_name='Closed_Callback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unauthorisedquoterequests',
            name='closed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Closed_requestsQuote', to='auth.user', verbose_name='Closedquote'),
            preserve_default=False,
        ),
    ]
