# Generated by Django 3.2.3 on 2024-04-02 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_genepool', '0015_auto_20240328_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthorisedcallbackrequests',
            name='closed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Closed_requests_Callback', to=settings.AUTH_USER_MODEL, verbose_name='Closed_Callback'),
        ),
        migrations.AlterField(
            model_name='unauthorisedquoterequests',
            name='closed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Closed_requestsQuote', to=settings.AUTH_USER_MODEL, verbose_name='Closedquote'),
        ),
    ]
